### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by caprinux** [qiuxiang/solidity-ls#15]
```c
➜ solidity-ls --version
/usr/local/lib/node_modules/solidity-ls/dist/index.js:69
      connection?.sendRequest(import_node.ShowMessageRequest.type, {
                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/solidity-ls/bin/solidity-ls.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

No idea what's the issue here :(

**Comment by caprinux** [comment]
wrong nodejs version

**Comment by culda** [comment]
What is the correct node version. I'm using node v20 and getting this when calling --version

`Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'`
